version: "2"

services:
  nginx:
    container_name: test_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    links:
      - php-fpm
    restart: unless-stopped
    stdin_open: true
    tty: true
  php-fpm:
    container_name: test_php
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    restart: unless-stopped
    stdin_open: true
    tty: true
